//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPlayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongSongCorrelation
    {
        public int Id { get; set; }
        public int PrimarySongId { get; set; }
        public int SecondarySongId { get; set; }
        public double CorrelationScore { get; set; }
    
        public virtual Song PrimarySong { get; set; }
        public virtual Song SecondarySong { get; set; }
    }
}
